### ISSUE TITLE
s_connect.js:33

### ISSUE THREAD

**Issue by Xrailer** [DOSexample/TS2#4]
c:\ts2\login\s_connect.js:33
                console.log('Recv 3',uCheckDataState, data);
                                     ^

ReferenceError: uCheckDataState is not defined
    at Socket.<anonymous> (c:\ts2\login\s_connect.js:33:24)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:559:20)

**Comment by DOSexample** [comment]
delete it
